//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiumLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexiumLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Reg.exe add &quot;HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync&quot; /v &quot;SyncPolicy&quot; /t REG_DWORD /d &quot;5&quot; /f
        /// Reg.exe delete &quot;HKCU\System\GameConfigStore\Parents&quot; /f
        /// Reg.exe delete &quot;HKCU\System\GameConfigStore\Children&quot; /f
        /// Reg.exe delete &quot;HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SuggestedApps&quot; /f
        /// Reg.exe delete &quot;HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\Subscriptions&quot; /f
        /// Reg.exe delete &quot;HKCU\SOFTWARE\Microsoft\Siuf\Rules&quot; /v &quot;PeriodInNano [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string boost {
            get {
                return ResourceManager.GetString("boost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg.exe add &quot;HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces&quot; /v &quot;TCPNoDelay&quot; /t REG_DWORD /d &quot;1616&quot; /f
        ///Reg.exe add &quot;HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces&quot; /v &quot;TcpAckFrequency&quot; /t REG_DWORD /d &quot;1616&quot; /f
        ///Reg.exe add &quot;HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces&quot; /v &quot;TcpDelAckTicks&quot; /t REG_DWORD /d &quot;0&quot; /f
        ///Reg.exe add &quot;HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces&quot; /v &quot;MTU&quot; /t REG_DWORD /d &quot;5376&quot; /f
        ///Reg.exe add &quot;HKLM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string internet {
            get {
                return ResourceManager.GetString("internet", resourceCulture);
            }
        }
    }
}
